"""012 — Reconcile schema drift between models and the actual migrated DB.

Freeze item #5 (module smoke + integration testing) found that several
models were redesigned after their migration (002_complete_schema) was
written, and no follow-up migration was ever generated to catch the DB up —
this project's migrations have always been hand-written; `alembic
revision --autogenerate` had never been run here before (added
alembic/script.py.mako, previously absent, to make that possible).

Concretely, before this migration: creating a bid decision, an award
simulation, a past-performance record, or reading agent-run/invoice history
all 500'd (`UndefinedColumnError`) — the model's INSERT/SELECT referenced
columns the live table never had. Five tables the models define
(`OpportunityNote`, `OpportunityWatch`, `BidDecisionFactor`,
`AwardSimulationSection`, `PastPerformanceTag`) were never migrated at all.

This is the autogenerated diff, reviewed and applied as-is with one
exception: the diff wanted to drop the `tenant_invites.tenant_id -> tenants`
FK because the model never declared it — every other tenant-scoped table
(e.g. AuditLog) does. That was a model bug, not an intentional gap; fixed
the model to add the FK instead of dropping it from the DB (see
cios/models/tenant.py), so it does not appear in this diff.

The DROP COLUMNs here (e.g. bid_decisions.overall_score,
past_performances.description, agent_run_steps.output) remove an earlier,
now-superseded design of those tables per the *current* models — safe
pre-launch, with no production data to lose.

Revision ID: 012_reconcile_schema_drift
Revises: 011_wph_task_order_fair_opp
Create Date: 2026-07-24
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "012_reconcile_schema_drift"
down_revision = "011_wph_task_order_fair_opp"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "past_performance_tags",
        sa.Column("past_performance_id", sa.String(length=64), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=False),
        sa.Column("tag_type", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_past_performance_tags_tenant_id"),
        "past_performance_tags",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "award_simulation_sections",
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column("factor_name", sa.String(length=128), nullable=False),
        sa.Column("factor_weight", sa.Float(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("rating", sa.String(length=32), nullable=True),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("color_rating", sa.String(length=16), nullable=True),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("adjectival_rating", sa.String(length=32), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["simulation_id"], ["award_simulations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_award_simulation_sections_tenant_id"),
        "award_simulation_sections",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "bid_decision_factors",
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("factor_name", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["decision_id"], ["bid_decisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bid_decision_factors_tenant_id"),
        "bid_decision_factors",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "opportunity_notes",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("note_type", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_opportunity_notes_tenant_id"), "opportunity_notes", ["tenant_id"], unique=False
    )
    op.create_table(
        "opportunity_watches",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("notify_on_change", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_opportunity_watches_tenant_id"), "opportunity_watches", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_watch", "opportunity_watches", ["tenant_id", "opportunity_id", "user_id"], unique=True
    )
    op.add_column("agent_run_steps", sa.Column("step_index", sa.Integer(), nullable=False))
    op.add_column(
        "agent_run_steps",
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
    )
    op.add_column(
        "agent_run_steps",
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "agent_run_steps",
        sa.Column("output_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "agent_run_steps",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "agent_run_steps", "step_name", existing_type=sa.VARCHAR(length=128), nullable=False
    )
    op.alter_column(
        "agent_run_steps", "agent_name", existing_type=sa.VARCHAR(length=128), nullable=False
    )
    op.alter_column(
        "agent_run_steps",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_ars_run"), table_name="agent_run_steps")
    op.create_index(
        op.f("ix_agent_run_steps_tenant_id"), "agent_run_steps", ["tenant_id"], unique=False
    )
    op.drop_column("agent_run_steps", "step_number")
    op.drop_column("agent_run_steps", "output")
    op.drop_column("agent_run_steps", "model_used")
    op.drop_column("agent_run_steps", "input_tokens")
    op.drop_column("agent_run_steps", "output_tokens")
    op.add_column("agent_runs", sa.Column("triggered_by", sa.UUID(), nullable=True))
    op.add_column(
        "agent_runs",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "agent_runs", "resource_type", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    op.alter_column("agent_runs", "status", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.alter_column(
        "agent_runs",
        "rule_citations",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "agent_runs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_ar_tenant_resource"), table_name="agent_runs")
    op.create_index("idx_ar_resource", "agent_runs", ["resource_type", "resource_id"], unique=False)
    op.create_index("idx_ar_tenant_type", "agent_runs", ["tenant_id", "agent_type"], unique=False)
    op.create_index(op.f("ix_agent_runs_tenant_id"), "agent_runs", ["tenant_id"], unique=False)
    op.alter_column(
        "api_keys", "scopes", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False
    )
    op.alter_column("api_keys", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "api_keys",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "api_keys",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "award_simulations",
        sa.Column("source_selection_authority", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "award_simulations",
        sa.Column(
            "weaknesses",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column(
        "award_simulations", "status", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    op.alter_column(
        "award_simulations", "simulation_type", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    op.alter_column(
        "award_simulations",
        "evaluation_methodology",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "award_simulations",
        "evaluation_factors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "award_simulations",
        "significant_weaknesses",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "award_simulations",
        "deficiencies",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "award_simulations",
        "strengths",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "award_simulations",
        "risks",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "award_simulations",
        "red_team_comments",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "award_simulations",
        "suggested_improvements",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "award_simulations",
        "competitor_analysis",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "award_simulations", "rule_pack", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    op.alter_column(
        "award_simulations",
        "rule_citations",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "award_simulations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "award_simulations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_award_simulations_tenant_id"), "award_simulations", ["tenant_id"], unique=False
    )
    op.add_column("bid_decisions", sa.Column("created_by", sa.UUID(), nullable=False))
    op.add_column("bid_decisions", sa.Column("capability_match_score", sa.Float(), nullable=True))
    op.add_column("bid_decisions", sa.Column("composite_score", sa.Float(), nullable=True))
    op.add_column("bid_decisions", sa.Column("recommendation", sa.String(length=16), nullable=True))
    op.add_column("bid_decisions", sa.Column("recommendation_rationale", sa.Text(), nullable=True))
    op.add_column("bid_decisions", sa.Column("decided_by", sa.UUID(), nullable=True))
    op.add_column(
        "bid_decisions",
        sa.Column(
            "alternatives",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "bid_decisions",
        sa.Column(
            "risks",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column(
        "bid_decisions",
        "human_decision",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=16),
        existing_nullable=True,
    )
    op.alter_column(
        "bid_decisions",
        "scoring_weights",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "bid_decisions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "bid_decisions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_bd_tenant_opp"), table_name="bid_decisions")
    op.create_index(
        "idx_bid_decision_tenant_opp",
        "bid_decisions",
        ["tenant_id", "opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bid_decisions_tenant_id"), "bid_decisions", ["tenant_id"], unique=False
    )
    op.drop_column("bid_decisions", "decision")
    op.drop_column("bid_decisions", "overall_score")
    op.drop_column("bid_decisions", "capability_score")
    op.drop_column("bid_decisions", "risk_factors")
    op.drop_column("bid_decisions", "opportunity_title")
    op.drop_column("bid_decisions", "rationale")
    op.drop_column("bid_decisions", "analyzed_at")
    op.drop_column("bid_decisions", "go_no_go_threshold")
    op.alter_column("capabilities", "is_certified", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "capabilities",
        "certifications",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "capabilities",
        "supporting_evidence",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "capabilities",
        "naics_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "capabilities",
        "psc_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "capabilities",
        "tools_and_technologies",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "capabilities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "capabilities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_capabilities_tenant_id"), "capabilities", ["tenant_id"], unique=False)
    op.alter_column(
        "capability_gaps", "severity", existing_type=sa.VARCHAR(length=16), nullable=False
    )
    op.alter_column(
        "capability_gaps",
        "remediation_options",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "capability_gaps", "status", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    op.alter_column(
        "capability_gaps",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "capability_gaps",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_capability_gaps_tenant_id"), "capability_gaps", ["tenant_id"], unique=False
    )
    op.alter_column(
        "competitor_intelligence",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competitor_intelligence",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_competitor_intelligence_tenant_id"),
        "competitor_intelligence",
        ["tenant_id"],
        unique=False,
    )
    op.alter_column(
        "competitors",
        "naics_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "competitors",
        "known_strengths",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "competitors",
        "known_weaknesses",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "competitors",
        "past_awards",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "competitors",
        "agency_relationships",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "competitors", "threat_level", existing_type=sa.VARCHAR(length=16), nullable=False
    )
    op.alter_column(
        "competitors",
        "socioeconomic_statuses",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "competitors",
        "active_clearances",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "competitors",
        "certifications",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "competitors", "tags", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False
    )
    op.alter_column(
        "competitors",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competitors",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_competitors_tenant_id"), "competitors", ["tenant_id"], unique=False)
    op.add_column("invoices", sa.Column("invoice_pdf_url", sa.String(length=512), nullable=True))
    op.add_column("invoices", sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "invoices",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "invoices", "stripe_invoice_id", existing_type=sa.VARCHAR(length=128), nullable=False
    )
    op.alter_column(
        "invoices",
        "amount_due",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "amount_paid",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "invoices",
        "currency",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.String(length=3),
        nullable=False,
    )
    op.alter_column("invoices", "status", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.alter_column(
        "invoices",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_inv_tenant"), table_name="invoices")
    op.create_index(op.f("ix_invoices_tenant_id"), "invoices", ["tenant_id"], unique=False)
    op.drop_column("invoices", "invoice_pdf")
    op.add_column("knowledge_chunks", sa.Column("content", sa.Text(), nullable=False))
    op.add_column(
        "knowledge_chunks",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "knowledge_chunks",
        "extra_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "knowledge_chunks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_qdrant_point_id"),
        "knowledge_chunks",
        ["qdrant_point_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_chunks_tenant_id"), "knowledge_chunks", ["tenant_id"], unique=False
    )
    op.drop_column("knowledge_chunks", "text")
    op.alter_column(
        "knowledge_documents",
        "extra_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "vectorization_status",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
    )
    op.alter_column(
        "knowledge_documents", "is_vectorized", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "knowledge_documents", "chunk_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "knowledge_documents",
        "tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "knowledge_documents", "is_confidential", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "knowledge_documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "knowledge_documents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_knowledge_documents_content_hash"),
        "knowledge_documents",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_tenant_id"), "knowledge_documents", ["tenant_id"], unique=False
    )
    op.alter_column(
        "opportunities",
        "naics_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "opportunities",
        "psc_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("opportunities", "currency", existing_type=sa.VARCHAR(length=3), nullable=False)
    op.alter_column("opportunities", "status", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.alter_column(
        "opportunities", "pipeline_stage", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    op.alter_column(
        "opportunities",
        "evaluation_criteria",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "opportunities",
        "key_requirements",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "opportunities",
        "anticipated_competitors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "opportunities",
        "procurement_rule_pack",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "opportunities",
        "attachments",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("opportunities", "is_archived", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "opportunities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "opportunities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_opportunities_external_id"), "opportunities", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_solicitation_number"),
        "opportunities",
        ["solicitation_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunities_tenant_id"), "opportunities", ["tenant_id"], unique=False
    )
    op.add_column(
        "past_performances", sa.Column("customer_name", sa.String(length=256), nullable=False)
    )
    op.add_column(
        "past_performances", sa.Column("customer_agency", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "past_performances", sa.Column("contract_type", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "past_performances",
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
    )
    op.add_column(
        "past_performances", sa.Column("period_start", sa.String(length=32), nullable=True)
    )
    op.add_column("past_performances", sa.Column("period_end", sa.String(length=32), nullable=True))
    op.add_column("past_performances", sa.Column("scope_of_work", sa.Text(), nullable=True))
    op.add_column(
        "past_performances",
        sa.Column(
            "key_accomplishments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "challenges_overcome",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "outcomes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "relevance_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "naics_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "psc_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("past_performances", sa.Column("quality_rating", sa.Float(), nullable=True))
    op.add_column("past_performances", sa.Column("schedule_rating", sa.Float(), nullable=True))
    op.add_column("past_performances", sa.Column("cost_rating", sa.Float(), nullable=True))
    op.add_column("past_performances", sa.Column("management_rating", sa.Float(), nullable=True))
    op.add_column("past_performances", sa.Column("poc_name", sa.String(length=256), nullable=True))
    op.add_column("past_performances", sa.Column("poc_email", sa.String(length=256), nullable=True))
    op.add_column("past_performances", sa.Column("poc_phone", sa.String(length=32), nullable=True))
    op.add_column(
        "past_performances",
        sa.Column("prime_or_sub", sa.String(length=16), server_default="prime", nullable=False),
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "teaming_partners",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column("is_verified", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.alter_column(
        "past_performances",
        "contract_number",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "past_performances", "is_confidential", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "past_performances",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "past_performances",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_pp_tenant"), table_name="past_performances")
    op.create_index("idx_pp_relevance", "past_performances", ["relevance_score"], unique=False)
    op.create_index(
        "idx_pp_tenant_type", "past_performances", ["tenant_id", "contract_type"], unique=False
    )
    op.create_index(
        op.f("ix_past_performances_contract_number"),
        "past_performances",
        ["contract_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_past_performances_tenant_id"), "past_performances", ["tenant_id"], unique=False
    )
    op.drop_column("past_performances", "period_of_performance_end")
    op.drop_column("past_performances", "naics_code")
    op.drop_column("past_performances", "agency")
    op.drop_column("past_performances", "ppirs_rating")
    op.drop_column("past_performances", "key_personnel")
    op.drop_column("past_performances", "subcontractors")
    op.drop_column("past_performances", "place_of_performance")
    op.drop_column("past_performances", "tags")
    op.drop_column("past_performances", "description")
    op.drop_column("past_performances", "period_of_performance_start")
    op.add_column(
        "pir_ai_analyses", sa.Column("ai_model_version", sa.String(length=64), nullable=True)
    )
    op.alter_column(
        "pir_ai_analyses",
        "evidence",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.create_index(
        op.f("ix_pir_ai_analyses_company_id"), "pir_ai_analyses", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_pir_ai_analyses_tenant_id"), "pir_ai_analyses", ["tenant_id"], unique=False
    )
    op.drop_column("pir_ai_analyses", "risks")
    op.drop_column("pir_ai_analyses", "assumptions")
    op.drop_column("pir_ai_analyses", "rule_citations")
    op.drop_column("pir_ai_analyses", "alternatives")
    op.drop_index(op.f("idx_pir_company_domain"), table_name="pir_companies")
    op.create_index(op.f("ix_pir_companies_domain"), "pir_companies", ["domain"], unique=False)
    op.create_index(
        op.f("ix_pir_companies_overall_signal_score"),
        "pir_companies",
        ["overall_signal_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pir_companies_tenant_id"), "pir_companies", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_pir_saved_searches_tenant_id"), "pir_saved_searches", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_pir_scan_jobs_tenant_id"), "pir_scan_jobs", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_pir_signals_company_id"), "pir_signals", ["company_id"], unique=False)
    op.create_index(op.f("ix_pir_signals_tenant_id"), "pir_signals", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_pir_watchlists_tenant_id"), "pir_watchlists", ["tenant_id"], unique=False
    )
    op.drop_index(op.f("idx_platform_admins_email"), table_name="platform_admins")
    op.drop_constraint(op.f("platform_admins_email_key"), "platform_admins", type_="unique")
    op.create_index(op.f("ix_platform_admins_email"), "platform_admins", ["email"], unique=True)
    op.alter_column("subscriptions", "status", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.alter_column("subscriptions", "seats", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "subscriptions",
        "features",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "subscriptions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index("idx_sub_stripe_id", "subscriptions", ["stripe_subscription_id"], unique=False)
    op.alter_column(
        "teaming_partners",
        "naics_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "teaming_partners",
        "psc_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "teaming_partners",
        "capabilities",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "teaming_partners",
        "socioeconomic_status",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "teaming_partners", "active_agreements", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "teaming_partners", "relationship_strength", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "teaming_partners",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "teaming_partners",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_teaming_partners_tenant_id"), "teaming_partners", ["tenant_id"], unique=False
    )
    op.alter_column(
        "teaming_recommendations",
        "prime_or_sub",
        existing_type=sa.VARCHAR(length=16),
        nullable=False,
    )
    op.alter_column(
        "teaming_recommendations",
        "team_structure",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "teaming_recommendations",
        "capability_gaps_addressed",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "teaming_recommendations",
        "recommended_partners",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "teaming_recommendations",
        "risks",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "teaming_recommendations", "status", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    op.alter_column(
        "teaming_recommendations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "teaming_recommendations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_teaming_recommendations_tenant_id"),
        "teaming_recommendations",
        ["tenant_id"],
        unique=False,
    )
    op.add_column(
        "tenant_invites",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    op.alter_column("tenant_invites", "role", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.alter_column(
        "tenant_invites",
        "token",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=256),
        existing_nullable=False,
    )
    op.alter_column("tenant_invites", "invited_by", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "tenant_invites",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("tenant_members", "role", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.alter_column("tenant_members", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "tenant_members",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenant_members",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_tm_user_id"), table_name="tenant_members")
    op.drop_constraint(op.f("uq_tenant_member"), "tenant_members", type_="unique")
    op.create_index("uq_tenant_member", "tenant_members", ["tenant_id", "user_id"], unique=True)
    op.create_index(op.f("ix_tenant_members_user_id"), "tenant_members", ["user_id"], unique=False)
    op.alter_column("tenants", "plan", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.alter_column("tenants", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "tenants", "settings", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False
    )
    op.alter_column(
        "tenants",
        "naics_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "tenants",
        "small_business_designations",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "tenants",
        "primary_jurisdictions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "tenants",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenants",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_tenants_slug"), table_name="tenants")
    op.drop_constraint(op.f("tenants_slug_key"), "tenants", type_="unique")
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_index(
        op.f("ix_wph_alignments_contractor_id"), "wph_alignments", ["contractor_id"], unique=False
    )
    op.create_index(
        op.f("ix_wph_alignments_profile_id"), "wph_alignments", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_wph_alignments_solicitation_id"),
        "wph_alignments",
        ["solicitation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wph_alignments_tenant_id"), "wph_alignments", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_wph_assessments_profile_id"), "wph_assessments", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_wph_assessments_solicitation_id"),
        "wph_assessments",
        ["solicitation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wph_assessments_tenant_id"), "wph_assessments", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_wph_contractors_tenant_id"), "wph_contractors", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_wph_evidence_documents_solicitation_id"),
        "wph_evidence_documents",
        ["solicitation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wph_evidence_documents_tenant_id"),
        "wph_evidence_documents",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wph_profile_attributes_profile_id"),
        "wph_profile_attributes",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wph_profile_attributes_tenant_id"),
        "wph_profile_attributes",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wph_profiles_solicitation_id"), "wph_profiles", ["solicitation_id"], unique=False
    )
    op.create_index(op.f("ix_wph_profiles_tenant_id"), "wph_profiles", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_wph_signals_document_id"), "wph_signals", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_wph_signals_solicitation_id"), "wph_signals", ["solicitation_id"], unique=False
    )
    op.create_index(op.f("ix_wph_signals_tenant_id"), "wph_signals", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_wph_solicitations_opportunity_id"),
        "wph_solicitations",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wph_solicitations_tenant_id"), "wph_solicitations", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wph_solicitations_tenant_id"), table_name="wph_solicitations")
    op.drop_index(op.f("ix_wph_solicitations_opportunity_id"), table_name="wph_solicitations")
    op.drop_index(op.f("ix_wph_signals_tenant_id"), table_name="wph_signals")
    op.drop_index(op.f("ix_wph_signals_solicitation_id"), table_name="wph_signals")
    op.drop_index(op.f("ix_wph_signals_document_id"), table_name="wph_signals")
    op.drop_index(op.f("ix_wph_profiles_tenant_id"), table_name="wph_profiles")
    op.drop_index(op.f("ix_wph_profiles_solicitation_id"), table_name="wph_profiles")
    op.drop_index(op.f("ix_wph_profile_attributes_tenant_id"), table_name="wph_profile_attributes")
    op.drop_index(op.f("ix_wph_profile_attributes_profile_id"), table_name="wph_profile_attributes")
    op.drop_index(op.f("ix_wph_evidence_documents_tenant_id"), table_name="wph_evidence_documents")
    op.drop_index(
        op.f("ix_wph_evidence_documents_solicitation_id"), table_name="wph_evidence_documents"
    )
    op.drop_index(op.f("ix_wph_contractors_tenant_id"), table_name="wph_contractors")
    op.drop_index(op.f("ix_wph_assessments_tenant_id"), table_name="wph_assessments")
    op.drop_index(op.f("ix_wph_assessments_solicitation_id"), table_name="wph_assessments")
    op.drop_index(op.f("ix_wph_assessments_profile_id"), table_name="wph_assessments")
    op.drop_index(op.f("ix_wph_alignments_tenant_id"), table_name="wph_alignments")
    op.drop_index(op.f("ix_wph_alignments_solicitation_id"), table_name="wph_alignments")
    op.drop_index(op.f("ix_wph_alignments_profile_id"), table_name="wph_alignments")
    op.drop_index(op.f("ix_wph_alignments_contractor_id"), table_name="wph_alignments")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.create_unique_constraint(
        op.f("tenants_slug_key"), "tenants", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_tenants_slug"), "tenants", ["slug"], unique=False)
    op.alter_column(
        "tenants",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenants",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenants",
        "primary_jurisdictions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "tenants",
        "small_business_designations",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "tenants",
        "naics_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "tenants", "settings", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True
    )
    op.alter_column("tenants", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("tenants", "plan", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.drop_index(op.f("ix_tenant_members_user_id"), table_name="tenant_members")
    op.drop_index("uq_tenant_member", table_name="tenant_members")
    op.create_unique_constraint(
        op.f("uq_tenant_member"),
        "tenant_members",
        ["tenant_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_tm_user_id"), "tenant_members", ["user_id"], unique=False)
    op.alter_column(
        "tenant_members",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenant_members",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("tenant_members", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("tenant_members", "role", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.alter_column(
        "tenant_invites",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("tenant_invites", "invited_by", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "tenant_invites",
        "token",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column("tenant_invites", "role", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.drop_column("tenant_invites", "updated_at")
    op.drop_index(
        op.f("ix_teaming_recommendations_tenant_id"), table_name="teaming_recommendations"
    )
    op.alter_column(
        "teaming_recommendations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "teaming_recommendations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "teaming_recommendations", "status", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    op.alter_column(
        "teaming_recommendations",
        "risks",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "teaming_recommendations",
        "recommended_partners",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "teaming_recommendations",
        "capability_gaps_addressed",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "teaming_recommendations",
        "team_structure",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "teaming_recommendations",
        "prime_or_sub",
        existing_type=sa.VARCHAR(length=16),
        nullable=True,
    )
    op.drop_index(op.f("ix_teaming_partners_tenant_id"), table_name="teaming_partners")
    op.alter_column(
        "teaming_partners",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "teaming_partners",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "teaming_partners", "relationship_strength", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "teaming_partners", "active_agreements", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "teaming_partners",
        "socioeconomic_status",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "teaming_partners",
        "capabilities",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "teaming_partners",
        "psc_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "teaming_partners",
        "naics_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_index("idx_sub_stripe_id", table_name="subscriptions")
    op.alter_column(
        "subscriptions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "subscriptions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "subscriptions",
        "features",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("subscriptions", "seats", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("subscriptions", "status", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.drop_index(op.f("ix_platform_admins_email"), table_name="platform_admins")
    op.create_unique_constraint(
        op.f("platform_admins_email_key"),
        "platform_admins",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_platform_admins_email"), "platform_admins", ["email"], unique=False)
    op.drop_index(op.f("ix_pir_watchlists_tenant_id"), table_name="pir_watchlists")
    op.drop_index(op.f("ix_pir_signals_tenant_id"), table_name="pir_signals")
    op.drop_index(op.f("ix_pir_signals_company_id"), table_name="pir_signals")
    op.drop_index(op.f("ix_pir_scan_jobs_tenant_id"), table_name="pir_scan_jobs")
    op.drop_index(op.f("ix_pir_saved_searches_tenant_id"), table_name="pir_saved_searches")
    op.drop_index(op.f("ix_pir_companies_tenant_id"), table_name="pir_companies")
    op.drop_index(op.f("ix_pir_companies_overall_signal_score"), table_name="pir_companies")
    op.drop_index(op.f("ix_pir_companies_domain"), table_name="pir_companies")
    op.create_index(op.f("idx_pir_company_domain"), "pir_companies", ["domain"], unique=False)
    op.add_column(
        "pir_ai_analyses",
        sa.Column(
            "alternatives",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "pir_ai_analyses",
        sa.Column(
            "rule_citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "pir_ai_analyses",
        sa.Column(
            "assumptions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "pir_ai_analyses",
        sa.Column(
            "risks",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_pir_ai_analyses_tenant_id"), table_name="pir_ai_analyses")
    op.drop_index(op.f("ix_pir_ai_analyses_company_id"), table_name="pir_ai_analyses")
    op.alter_column(
        "pir_ai_analyses",
        "evidence",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_column("pir_ai_analyses", "ai_model_version")
    op.add_column(
        "past_performances",
        sa.Column("period_of_performance_start", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "past_performances", sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "tags", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "place_of_performance", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "subcontractors",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column(
            "key_personnel",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "past_performances",
        sa.Column("ppirs_rating", sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    )
    op.add_column(
        "past_performances",
        sa.Column("agency", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    )
    op.add_column(
        "past_performances",
        sa.Column("naics_code", sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    )
    op.add_column(
        "past_performances",
        sa.Column("period_of_performance_end", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_past_performances_tenant_id"), table_name="past_performances")
    op.drop_index(op.f("ix_past_performances_contract_number"), table_name="past_performances")
    op.drop_index("idx_pp_tenant_type", table_name="past_performances")
    op.drop_index("idx_pp_relevance", table_name="past_performances")
    op.create_index(op.f("idx_pp_tenant"), "past_performances", ["tenant_id"], unique=False)
    op.alter_column(
        "past_performances",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "past_performances",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "past_performances", "is_confidential", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "past_performances",
        "contract_number",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=64),
        existing_nullable=True,
    )
    op.drop_column("past_performances", "is_verified")
    op.drop_column("past_performances", "teaming_partners")
    op.drop_column("past_performances", "prime_or_sub")
    op.drop_column("past_performances", "poc_phone")
    op.drop_column("past_performances", "poc_email")
    op.drop_column("past_performances", "poc_name")
    op.drop_column("past_performances", "management_rating")
    op.drop_column("past_performances", "cost_rating")
    op.drop_column("past_performances", "schedule_rating")
    op.drop_column("past_performances", "quality_rating")
    op.drop_column("past_performances", "psc_codes")
    op.drop_column("past_performances", "naics_codes")
    op.drop_column("past_performances", "relevance_factors")
    op.drop_column("past_performances", "metrics")
    op.drop_column("past_performances", "outcomes")
    op.drop_column("past_performances", "challenges_overcome")
    op.drop_column("past_performances", "key_accomplishments")
    op.drop_column("past_performances", "scope_of_work")
    op.drop_column("past_performances", "period_end")
    op.drop_column("past_performances", "period_start")
    op.drop_column("past_performances", "currency")
    op.drop_column("past_performances", "contract_type")
    op.drop_column("past_performances", "customer_agency")
    op.drop_column("past_performances", "customer_name")
    op.drop_index(op.f("ix_opportunities_tenant_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_solicitation_number"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_external_id"), table_name="opportunities")
    op.alter_column(
        "opportunities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "opportunities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("opportunities", "is_archived", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "opportunities",
        "attachments",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "opportunities", "procurement_rule_pack", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.alter_column(
        "opportunities",
        "anticipated_competitors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "opportunities",
        "key_requirements",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "opportunities",
        "evaluation_criteria",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "opportunities", "pipeline_stage", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    op.alter_column("opportunities", "status", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.alter_column("opportunities", "currency", existing_type=sa.VARCHAR(length=3), nullable=True)
    op.alter_column(
        "opportunities",
        "psc_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "opportunities",
        "naics_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_index(op.f("ix_knowledge_documents_tenant_id"), table_name="knowledge_documents")
    op.drop_index(op.f("ix_knowledge_documents_content_hash"), table_name="knowledge_documents")
    op.alter_column(
        "knowledge_documents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "knowledge_documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "knowledge_documents", "is_confidential", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "knowledge_documents",
        "tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("knowledge_documents", "chunk_count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "knowledge_documents", "is_vectorized", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "knowledge_documents",
        "vectorization_status",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
    )
    op.alter_column(
        "knowledge_documents",
        "extra_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.add_column(
        "knowledge_chunks", sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_knowledge_chunks_tenant_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_qdrant_point_id"), table_name="knowledge_chunks")
    op.alter_column(
        "knowledge_chunks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "knowledge_chunks",
        "extra_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_column("knowledge_chunks", "updated_at")
    op.drop_column("knowledge_chunks", "content")
    op.add_column(
        "invoices",
        sa.Column("invoice_pdf", sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_invoices_tenant_id"), table_name="invoices")
    op.create_index(op.f("idx_inv_tenant"), "invoices", ["tenant_id"], unique=False)
    op.alter_column(
        "invoices",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("invoices", "status", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.alter_column(
        "invoices",
        "currency",
        existing_type=sa.String(length=3),
        type_=sa.VARCHAR(length=8),
        nullable=True,
    )
    op.alter_column(
        "invoices",
        "amount_paid",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "invoices",
        "amount_due",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices", "stripe_invoice_id", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.drop_column("invoices", "updated_at")
    op.drop_column("invoices", "paid_at")
    op.drop_column("invoices", "invoice_pdf_url")
    op.drop_index(op.f("ix_competitors_tenant_id"), table_name="competitors")
    op.alter_column(
        "competitors",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competitors",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competitors", "tags", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True
    )
    op.alter_column(
        "competitors",
        "certifications",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "competitors",
        "active_clearances",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "competitors",
        "socioeconomic_statuses",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "competitors", "threat_level", existing_type=sa.VARCHAR(length=16), nullable=True
    )
    op.alter_column(
        "competitors",
        "agency_relationships",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "competitors",
        "past_awards",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "competitors",
        "known_weaknesses",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "competitors",
        "known_strengths",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "competitors",
        "naics_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_competitor_intelligence_tenant_id"), table_name="competitor_intelligence"
    )
    op.alter_column(
        "competitor_intelligence",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competitor_intelligence",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_capability_gaps_tenant_id"), table_name="capability_gaps")
    op.alter_column(
        "capability_gaps",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "capability_gaps",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("capability_gaps", "status", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.alter_column(
        "capability_gaps",
        "remediation_options",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "capability_gaps", "severity", existing_type=sa.VARCHAR(length=16), nullable=True
    )
    op.drop_index(op.f("ix_capabilities_tenant_id"), table_name="capabilities")
    op.alter_column(
        "capabilities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "capabilities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "capabilities",
        "tools_and_technologies",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "capabilities",
        "psc_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "capabilities",
        "naics_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "capabilities",
        "supporting_evidence",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "capabilities",
        "certifications",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("capabilities", "is_certified", existing_type=sa.BOOLEAN(), nullable=True)
    op.add_column(
        "bid_decisions",
        sa.Column(
            "go_no_go_threshold",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "bid_decisions",
        sa.Column(
            "analyzed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "bid_decisions", sa.Column("rationale", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "bid_decisions",
        sa.Column("opportunity_title", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    )
    op.add_column(
        "bid_decisions",
        sa.Column(
            "risk_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "bid_decisions",
        sa.Column(
            "capability_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "bid_decisions",
        sa.Column(
            "overall_score", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "bid_decisions",
        sa.Column("decision", sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_bid_decisions_tenant_id"), table_name="bid_decisions")
    op.drop_index("idx_bid_decision_tenant_opp", table_name="bid_decisions")
    op.create_index(
        op.f("idx_bd_tenant_opp"), "bid_decisions", ["tenant_id", "opportunity_id"], unique=False
    )
    op.alter_column(
        "bid_decisions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "bid_decisions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "bid_decisions",
        "scoring_weights",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "bid_decisions",
        "human_decision",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=32),
        existing_nullable=True,
    )
    op.drop_column("bid_decisions", "risks")
    op.drop_column("bid_decisions", "alternatives")
    op.drop_column("bid_decisions", "decided_by")
    op.drop_column("bid_decisions", "recommendation_rationale")
    op.drop_column("bid_decisions", "recommendation")
    op.drop_column("bid_decisions", "composite_score")
    op.drop_column("bid_decisions", "capability_match_score")
    op.drop_column("bid_decisions", "created_by")
    op.drop_index(op.f("ix_award_simulations_tenant_id"), table_name="award_simulations")
    op.alter_column(
        "award_simulations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "award_simulations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "award_simulations",
        "rule_citations",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "award_simulations", "rule_pack", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.alter_column(
        "award_simulations",
        "competitor_analysis",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "award_simulations",
        "suggested_improvements",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "award_simulations",
        "red_team_comments",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "award_simulations",
        "risks",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "award_simulations",
        "strengths",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "award_simulations",
        "deficiencies",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "award_simulations",
        "significant_weaknesses",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "award_simulations",
        "evaluation_factors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "award_simulations",
        "evaluation_methodology",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.alter_column(
        "award_simulations", "simulation_type", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.alter_column(
        "award_simulations", "status", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    op.drop_column("award_simulations", "weaknesses")
    op.drop_column("award_simulations", "source_selection_authority")
    op.alter_column(
        "api_keys",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "api_keys",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("api_keys", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "api_keys", "scopes", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True
    )
    op.drop_index(op.f("ix_agent_runs_tenant_id"), table_name="agent_runs")
    op.drop_index("idx_ar_tenant_type", table_name="agent_runs")
    op.drop_index("idx_ar_resource", table_name="agent_runs")
    op.create_index(
        op.f("idx_ar_tenant_resource"),
        "agent_runs",
        ["tenant_id", "resource_type", "resource_id"],
        unique=False,
    )
    op.alter_column(
        "agent_runs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "agent_runs",
        "rule_citations",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("agent_runs", "status", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.alter_column(
        "agent_runs", "resource_type", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.drop_column("agent_runs", "updated_at")
    op.drop_column("agent_runs", "triggered_by")
    op.add_column(
        "agent_run_steps",
        sa.Column("output_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agent_run_steps",
        sa.Column("input_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agent_run_steps",
        sa.Column("model_used", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agent_run_steps",
        sa.Column(
            "output", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "agent_run_steps",
        sa.Column("step_number", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_agent_run_steps_tenant_id"), table_name="agent_run_steps")
    op.create_index(op.f("idx_ars_run"), "agent_run_steps", ["agent_run_id"], unique=False)
    op.alter_column(
        "agent_run_steps",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "agent_run_steps", "agent_name", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.alter_column(
        "agent_run_steps", "step_name", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.drop_column("agent_run_steps", "updated_at")
    op.drop_column("agent_run_steps", "output_data")
    op.drop_column("agent_run_steps", "input_data")
    op.drop_column("agent_run_steps", "status")
    op.drop_column("agent_run_steps", "step_index")
    op.drop_index("uq_watch", table_name="opportunity_watches")
    op.drop_index(op.f("ix_opportunity_watches_tenant_id"), table_name="opportunity_watches")
    op.drop_table("opportunity_watches")
    op.drop_index(op.f("ix_opportunity_notes_tenant_id"), table_name="opportunity_notes")
    op.drop_table("opportunity_notes")
    op.drop_index(op.f("ix_bid_decision_factors_tenant_id"), table_name="bid_decision_factors")
    op.drop_table("bid_decision_factors")
    op.drop_index(
        op.f("ix_award_simulation_sections_tenant_id"), table_name="award_simulation_sections"
    )
    op.drop_table("award_simulation_sections")
    op.drop_index(op.f("ix_past_performance_tags_tenant_id"), table_name="past_performance_tags")
    op.drop_table("past_performance_tags")
    # ### end Alembic commands ###
